### ISSUE TITLE
How to get latest build?

### ISSUE THREAD

**Issue by tapper82** [noddos/noddos#38]
Hi the build at https://noddos.io/dist/lede/releases/snapshots/arch/mvebu/packages/master/noddos_master-1_arm_cortex-a9_vfpv3.ipk is from the 18th of oct. Will you be building the latest build so I can test the fixes?

**Comment by StevenHessing** [comment]
Yes, I'll enable automatic builds of the master branch so we have nightly builds. I do merge quite a bit to master so at this time no assurances on the stability of the builds in master.

**Comment by StevenHessing** [comment]
Master branch and v0.5.5 builds (all but the same at this time) are now available but only for 17.01.3 and 17.01.4 at this time. I had some issues building against the Lede snapshot. 

I've also submitted a PR for the openwrt/packages master branch: https://github.com/openwrt/packages/pull/5041

Builds are not yet fully automated, that will need some changes to my build system and maybe some Jenkins. For now I'll kick them off manually for the master whenever there is something useful to share and whenever there is a new release.
