### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by Strykar** [noddos/noddos#55]
```
# /usr/bin/getnoddosdeviceprofiles; if [ $? -gt 0 ]; then service noddos reload; fi
Error getting checksum file: https://www.noddos.io/config/DeviceProfiles.json.sha256
```
The last commit was on Sept 12, 2019, is the project dead?
The instructions speak of a place to specify the LAN/Brdige itnerfaces, Openwrt 19.  luci does not show any.

**Comment by byoda** [comment]
Hi,

 

I’m not in a position to maintain the project so it should be considered dead.

 

*	Steven

**Comment by Strykar** [comment]
Thanks for clearing that up.
